"use client";

import { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import CompanySearch from "../components/CompanySearch";
import SignalStrip from "../components/SignalStrip";
import RatioTable from "../components/RatioTable";
import RedFlagList from "../components/RedFlagList";
import DownloadButtons from "../components/DownloadButtons";
import PriceChart from "../components/PriceChart";
import ProgressIndicator from "../components/ProgressIndicator";
import { analyzeCompany, AnalyzeResponse, pingHealth } from "../lib/api";

export default function Home() {
  const [data, setData] = useState<AnalyzeResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const lastRequest = useRef<{ name: string; symbol: string; exchange: string } | null>(null);

  // Fire-and-forget: wake up a sleeping Render free-tier instance as soon as
  // someone lands on the page, so it's more likely to be warm by the time
  // they actually submit a search.
  useEffect(() => {
    pingHealth();
  }, []);

  async function runAnalysis(companyName: string, nseSymbol: string, exchange: string) {
    lastRequest.current = { name: companyName, symbol: nseSymbol, exchange };
    setLoading(true);
    setError(null);
    setData(null);
    try {
      const result = await analyzeCompany(companyName, nseSymbol, exchange);
      setData(result);
    } catch (e: any) {
      setError(e.message || "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function handleRetry() {
    if (lastRequest.current) {
      runAnalysis(
        lastRequest.current.name,
        lastRequest.current.symbol,
        lastRequest.current.exchange
      );
    }
  }

  return (
    <div className="container">
      <div className="masthead">
        <h1>Equity Research Assistant</h1>
        <span className="tag">BSE / NSE · AI-generated</span>
      </div>

      {!data && !loading && (
        <div className="hero">
          <p>
            Enter a listed company below to get a JPM/Nomura-style research
            note: five years of ratio trends, a CAPM-based cost of equity,
            volatility &amp; drawdown risk, rule-based red flags, and a
            backtest of the model&apos;s own forecast accuracy — plus a
            downloadable Excel workbook and PDF note.
          </p>
        </div>
      )}

      <CompanySearch onSubmit={runAnalysis} loading={loading} />

      {loading && <ProgressIndicator />}

      {error && (
        <div className="error-box">
          <div>{error}</div>
          <button className="retry-btn" onClick={handleRetry}>
            Try again
          </button>
        </div>
      )}

      {data && (
        <>
          <div className="section" style={{ marginTop: 32 }}>
            <h2>
              {data.company_name} ({data.symbol}) · {data.exchange}
            </h2>
            <SignalStrip data={data} />
          </div>

          <div className="section">
            <h2>5-Year Price History</h2>
            <PriceChart data={data.price_history} />
          </div>

          <div className="section">
            <h2>Research Note</h2>
            <div className="note-text">
              <ReactMarkdown>{data.summary}</ReactMarkdown>
            </div>
          </div>

          <div className="section">
            <h2>5-Year Ratio Trends</h2>
            <RatioTable ratios={data.ratios} />
          </div>

          <div className="section">
            <h2>Red Flags</h2>
            <RedFlagList flags={data.red_flags} />
          </div>

          <div className="section">
            <h2>Download Full Reports</h2>
            <DownloadButtons excelUrl={data.excel_url} pdfUrl={data.pdf_url} />
          </div>

          <div className="disclaimer">
            This note is generated by an automated pipeline combining public
            financial data with quantitative models (CAPM, historical
            volatility, rule-based red-flag checks). It is a research aid,
            not investment advice, and the backtest measures the model&apos;s
            own signal accuracy historically — not a trading strategy&apos;s
            returns.
          </div>
        </>
      )}

      <footer className="page-footer">
        Data: Yahoo Finance, Screener.in · Analysis is generated automatically
        and may contain errors — verify against primary sources before
        acting on it.
      </footer>
    </div>
  );
}
